---
title: "Implementation of the CAMERA-package"
author: "Søren Fjelstrup"
date: "12 apr 2019"
output: html_document
---

author: "Johannes Rainer, Søren Fjelstrup, Chiara Volani and Giuseppe Paglia"
graphics: yes
output:
  BiocStyle::html_document:
    toc_float: true
bibliography: references.bib
csl: biomed-central.csl
references:
- id: dummy
  title: no title
  author:
  - family: noname
    given: noname
---

```{r biocstyle, echo = FALSE, results='hide', message = FALSE}
library(BiocStyle)
BiocStyle::markdown()
```

**Modified**: `r file.info("vams_sex_pos.Rmd")$mtime`<br />
**Compiled**: `r date()`

```{r settings, echo = FALSE, results = "hide", message = FALSE, warning = FALSE}
#' Set general options
options(useFancyQuotes = FALSE)
set.seed(18011977)

#' Define paths:
filename <- "CAMERA package"
#' Path to save the images; remove all old images.
IMAGE_PATH <- paste0("images/", filename, "/")
if (file.exists(IMAGE_PATH)) 
    unlink(IMAGE_PATH, recursive = TRUE)
dir.create(IMAGE_PATH, recursive = TRUE)
#' Path to store RData files
RDATA_PATH <- paste0("data/RData/", filename, "/")
if (!file.exists(RDATA_PATH)) dir.create(RDATA_PATH, recursive = TRUE)

#' Get the number of cpus allocated or fall back to 3
ncores <- as.integer(Sys.getenv("SLURM_JOB_CPUS_PER_NODE", 3))
```

```{r load-data , results='hide', message = FALSE}
library(xcms)
library(RColorBrewer)
library(pander)
library(doParallel)
registerDoParallel(ncores)
register(DoparParam(), default = TRUE)
#' register(SerialParam())
library(SummarizedExperiment)
library(UpSetR)
library(pls)
library(caret)
library(CAMERA)

#' Load utility functions for the analysis
source("util-functions.R")

#' Define colors for the groups.
col_source <- brewer.pal(5, name = "Set1")[c(1, 2, 4, 5)]
names(col_source) <- c("RBC",           #' red
                       "plasma",        #' blue
                       "capillary",     #' purple
                       "venous")        #' orange

load("data/RData/vams_normalization/vams_pos.RData")
load("data/RData/vams_normalization/data_pos.RData")


```





```{r Own}

RDATA_PATH <- paste0("Output/", "CAMERA", "/")

data_pos_xcms <- as(data_pos,"xcmsSet")

an <- xsAnnotate(data_pos_xcms, polarity = "positive")
anGroupFWHM <- groupFWHM(an, perfwhm = 0.6) # group peaks by retention time
#anIsotopes <- findIsotopesWithValidation(anGroupFWHM) Currently not working,WHY?!
#Error in if (!isotopeProportionFits) { : missing value where TRUE/FALSE needed

#The group correlation step makes no difference in our data with the current options, might be needed to add in the future though
#anGroupCorr <- groupCorr(anGroupFWHM)
#anAdduct <- findAdducts(object = anGroupCorr, ppm = 10, mzabs = 0.01, polarity = "positive") # annotate adducts

file <- system.file('rules/primary_adducts_pos.csv', package = "CAMERA")
rules <- read.csv(file)
rules <- rules[1:3,]


anAdduct <- findAdducts(object = anGroupFWHM, ppm = 10, mzabs = 0.01, polarity = "positive",rules = rules) # annotate adducts
peakTable <- getPeaklist(anAdduct)
ExportTable <- peakTable[,c(1,4,209:211)]

write.table(as.matrix(ExportTable), file = paste0(RDATA_PATH, "Annotated.txt"),sep = "\t",row.names = FALSE)

write.table(anAdduct@annoID, file = paste0(RDATA_PATH, "AnnotatedID.txt"),sep = "\t",row.names = FALSE)

```

```{r Extraction-of-annotations}
library(stringr)
AnnoID <- peakTable[,210]

extractMass <-  function(x){
  if (length(x) ){
    x[seq(2, length(x), by=2)]
    
  } else
    NA
  
}

extractType <-  function(x){
  if (length(x) ){
    x[seq(1, length(x), by=2)]
    
  } else
    NA
  
}

monoIsotopicMassList <- lapply(strsplit(AnnoID,split = " "), extractMass)

AdductTypeList  <- lapply(strsplit(AnnoID,split = " "), extractType)
  

groupInfo <- cbind(monoIsotopicMassList,AdductTypeList)

colnames(groupInfo) <- c("monoIsotopicMass","AdductType")


#Error in validObject(object) : 
 # invalid class "MsFeatureData" object: Some of the indices in column 'peakidx'
#of element 'featureDefinitions' do not match rows of the 'chromPeaks' matrix!
#featureDefinitions(data_pos) <- cbind(featureDefinitions(data_pos),groupInfo)
#tmp <- cbind(featureDefinitions(data_pos),groupInfo)

```


```{r Grouping-ofAnnotations}
numericmonoIsotopicMass <- unique(as.numeric(unlist(monoIsotopicMassList)))

loc <- c()

for (n in 1:length(numericmonoIsotopicMass)) {
  
  loc[[n]] <- which(monoIsotopicMassList %in% numericmonoIsotopicMass[n])
  
}


  monoIsotopicMassList[loc[[2]]]
  
peakTable[loc[[2]],]


```
